version: '3.8'

services:
  db:
    image: postgres:15
    container_name: enron_postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mon_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:

