# Generated by Django 6.0.3 on 2026-03-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id_collaborateur', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=255, unique=True)),
                ('nom_collaborateur', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'collaborateur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dossier', models.CharField(max_length=255)),
                ('chemin_complet', models.TextField()),
                ('id_collaborateur', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'dossier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopMot',
            fields=[
                ('id_mot', models.AutoField(primary_key=True, serialize=False)),
                ('mot', models.CharField(max_length=100, unique=True)),
                ('occurrence', models.IntegerField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'top_mot',
                'ordering': ['-occurrence'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('corps_mail', models.TextField(null=True)),
                ('dossier', models.ForeignKey(db_column='id_dossier', on_delete=django.db.models.deletion.CASCADE, to='enron.dossier')),
                ('expediteur', models.ForeignKey(db_column='id_expediteur', on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='enron.collaborateur')),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id_destinataire', models.AutoField(primary_key=True, serialize=False)),
                ('type_envoie', models.CharField(max_length=10)),
                ('collaborateur', models.ForeignKey(db_column='id_collaborateur', on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='enron.collaborateur')),
                ('message', models.ForeignKey(db_column='id_message', on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='enron.message')),
            ],
            options={
                'db_table': 'destinataire',
                'managed': True,
            },
        ),
    ]
