# Generated by Django 6.0.3 on 2026-03-22 11:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enron', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['corps_mail'], name='corps_mail_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['date'], name='message_date_bc9370_idx'),
        ),
    ]
